[package]
name = "zed-common"
version = "0.1.0"
edition = "2021"

[features]
sqlite = []
postgres = []

[dependencies]
bs58 = "0.5.0"
chrono = { version = "0.4.31", features = ["serde"] }
hex = { version = "0.4.3", features = ["serde"] }
sha2 = "0.10.8"
